### ISSUE TITLE
[Feature request] Please add TLSA record type support

### ISSUE THREAD

**Issue by klaver** [atomia/atomiadns#20]
Hi Atomia,

We love your DNS API, it's working wonderful!

Recently we tried to enable DANE support for our domains, but the required recordtype does not seem to be allowed into the DNS zones.
Could you please fix this?

"got fault of type soap:InvalidParametersError.BadType: bad response for RestoreZone: ERROR:  TLSA is not an available type at /usr/share/perl5/Atomia/DNS/ServerHandler.pm line 773."

Thanks in advance!

**Comment by jimmybergman** [comment]
Added in 1.1.34 which is now available.
