### ISSUE TITLE
What is Atomia DNS exactly?

### ISSUE THREAD

**Issue by theronic** [atomia/atomiadns#26]
Hi! I'm hoping I can use Atomia, but I don't quite understand what it is.

Is Atomia a DNS server or does it talk to an existing cluster of DNS servers to manage their records? What problem does this solve? E.g. I want to host my own nameservers. Can I use Atomia for that? Or do I need to run an existing DNS server?

It's not clear to me from the README:

> Atomia DNS is a multi tenant system for handling large amounts of DNS data through programmatic interfaces.
> Atomia DNS also contains synchronization agents for making sure that this data hits all of your nameservers. Agents for PowerDNS and Bind-DLZ are included.

I could gleam some more from the cURL examples on the home page - an API to manage DNS entries in a database somewhere (where are they stored?), but my question above still stands.

**Comment by jimmybergman** [comment]
It is an API used to manage DNS entries, information about which nameservers you have attached to the system and functionality for keeping them in sync. It also has DNSSEC key management functionality. 

This normally runs on a control server not exposed to the internet directly. The actual data is stored in a PostgreSQL database either on this control server (more common) or somewhere else.

You then pick one of the supported nameservers for the actual DNS serving, almost everyone uses PowerDNS. On the nameservers a small sync agent is installed that makes sure all nameservers are in sync and up to date with the latest DNS zone data and DNSSEC key information.
