### ISSUE TITLE
官网还不支持centos7？

### ISSUE THREAD

**Issue by shuncon** [atomia/atomiadns#43]
官网还不支持centos7？

**Comment by sasa-mladenovic-troxo** [comment]
Officially not yet. It should work on RHEL7/CentOS7 but I can't guaranty it yet.
One thing to note is that AtomiaDNS is designed to work with the MySQL database. On RHEL7, MySQL is not available in official repos and it installs MariaDB as a replacement by default. It should work with MariaDB without issues, but, again, I'm not sure.

https://tecadmin.net/install-mysql-on-centos-redhat-and-fedora/
