### ISSUE TITLE
Project abandoned?

### ISSUE THREAD

**Issue by lima3w** [atomia/atomiadns#57]
Looking through the issues, it appears there are a lot of them that have been open for years and not fixed, including one pointing out that the install script is no longer accessible. 

There was a commit a week ago. Is this project dead? Does this project need help?

**Comment by sasa-mladenovic-troxo** [comment]
Sorry for the late answer.
The project is not abandoned. 
However, we are mainly adding features and fixes needed for our internal use. We will welcome any help people can offer, especially regarding the fixes in the Web user interface.

The biggest blocker at this point is #52 but we are working on a solution.

**Comment by tacerus** [comment]
Hi @sasa-mladenovic-troxo  - Would be sweet if you could fix the links on https://atomiadns.com/documentation/ - they lead to a GitHub 404, making one think that this is no longer maintained. Thanks for your cool work!

**Comment by sasa-mladenovic-troxo** [comment]
> Hi @sasa-mladenovic-troxo - Would be sweet if you could fix the links on https://atomiadns.com/documentation/ - they lead to a GitHub 404, making one think that this is no longer maintained. Thanks for your cool work!

Bah, I forgot to do that :(
It's fixed now, thanks.
